image:
  repository: keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/kubernetes-oomkill-exporter
  tag: 0.4.0
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 20m
    memory: 20Mi

metrics:
  port: 9102
  # Name of the Prometheus supposed to scrape the metrics.
  prometheus: 'kubernetes, openstack, infra-collector'

# Enable Prometheus alerts.
alerts:
  enabled: true
  # Name of the Prometheus to which the alerts will be assigned to.
  prometheus: kubernetes

tolerations:
  - operator: Exists
