apiVersion: v1
kind: ConfigMap

metadata:
  name: limes

data:
  policy.yaml: |
{{ .Files.Get "files/policy.yaml" | indent 4 }}
  limes.yaml: |
    clusters:
{{ toYaml .Values.limes.clusters | indent 6 }}
  migrate.sh: |
    #!/bin/sh
    set -euo pipefail
    limes migrate /etc/limes/limes.yaml
    exec tail -f /dev/null

{{- range $constraint_name, $constraint := .Values.limes.constraints }}
  constraints-{{ $constraint_name }}.yaml: |
{{ toYaml $constraint | indent 4 }}
{{- end }}
