dependencies:
  - name: es-master
    alias: es_master
    repository: file://vendor/es-master
    version: 2.0.0
    condition: es_master.enabled

  - name: es-client
    alias: es_client
    repository: file://vendor/es-client
    version: 2.0.0
    condition: es_client.enabled

  - name: es-data
    alias: es_data
    repository: file://vendor/es-data
    version: 2.0.1
    condition: es_data.enabled

  - name: es-manager
    alias: es_manager
    repository: file://vendor/es-manager
    version: 2.0.0
    condition: es_manager.enabled

  - name: kibana
    repository: file://vendor/kibana
    version: 2.0.0
    condition: kibana.enabled

  - name: fluent
    repository: file://vendor/fluent
    version: 2.0.0
    condition: fluent.enabled

  - name: fluent-audit-container
    alias: fluent_audit_container
    repository: file://vendor/fluent-audit-container
    version: 2.0.0
    condition: fluent_audit_container.enabled

  - name: fluent-systemd
    alias: fluent_systemd
    repository: file://vendor/fluent-systemd
    version: 2.0.0
    condition: fluent_systemd.enabled

  - name: fluent-vcenter
    alias: fluent_vcenter
    repository: file://vendor/fluent-vcenter
    version: 2.0.0
    condition: fluent_vcenter.enabled

  - name: fluent-scaleout
    alias: fluent_scaleout
    repository: file://vendor/fluent-scaleout
    version: 1.0.0
    condition: fluent_scaleout.enabled

  - name: logstash-audit-external
    alias: logstash_audit_external
    repository: file://vendor/logstash-audit-external
    version: 2.0.0
    condition: logstash_audit_external.enabled

  - name: logstash-audit-services
    alias: logstash_audit_services
    repository: file://vendor/logstash-audit-services
    version: 1.0.0
    condition: logstash_audit_services.enabled

  - name: wall-e
    alias: wall_e
    repository: file://vendor/wall-e
    version: 2.0.0
    condition: wall_e.enabled
