apiVersion: v1
kind: ConfigMap
metadata:
  name: cc3test-config
  namespace: {{ .Values.cc3test.namespace }}
data:
  config.yaml: |
    global:
      region: {{ .Values.global.region }}
      availability_zones:
{{ toYaml .Values.global.availability_zones | indent 8 }}
      netapp:
        filers:
{{ toYaml .Values.global.netapp.filers | indent 10 }}
      designate_mdns_external_ip: {{ .Values.global.designate_mdns_external_ip }}
    config:
{{ toYaml .Values.config | indent 6 }}
    workers:
{{ toYaml .Values.workers | indent 6 }}
    bind_pools:
{{ toYaml .Values.bind_pools | indent 6 }}