replicaCount: 2
image:
  repository: sapcc/maintenance-controller
  tag: 0.8
  pullPolicy: IfNotPresent
rbac:
  create: false
  serviceAccountName: default
config: null
flatcar-linux-update-agent:
  enabled: true
esx:
  enabled: false
  config: null
kubernikus:
  enabled: false
  config: null
  cloudconfig: cloud-config
