apiVersion: v1
kind: Secret
metadata:
  name: vcf-secret
data:
  pulumi_config_passphrase: {{ .Values.pulumi_config_passphrase | b64enc }}
  vmware_password: {{ .Values.vmware_password | b64enc }}
  {{- if hasKey .Values "esxi_password" }}
  esxi_password: {{ .Values.esxi_password | b64enc }}
  {{- end }}
  esxi_license_management: {{ .Values.global.esxi_license_management | b64enc }}
  esxi_license: {{ .Values.global.esxi_license | b64enc }}
  nsxt_license: {{ .Values.global.nsxt_license | b64enc }}
{{- if (contains "qa" .Values.global.region) }}
  os_password: {{  .Values.monsoon3.os_password | b64enc }}
  os_username: {{ .Values.monsoon3.os_username | b64enc }}
{{- else }}
  os_password: {{ .Values.hcp03.os_password | b64enc }}
  os_username: {{ .Values.hcp03.os_username | b64enc }}
{{- end }}
