apiVersion: v2
name: concourse-main
description: An umbrella chart for concourse ci
type: application
version: 7.6.0
appVersion: 7.6.0
dependencies:
- name: concourse
  version: 16.1.2
  repository: "https://concourse-charts.storage.googleapis.com"
- name: kubernetes-ingress
  version: 1.17.11
  repository: "https://haproxytech.github.io/helm-charts"
  condition: gitResourceProxy.enabled
