apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkIngressAnnotations
metadata:
  name: ingressannotations
  labels:
    on-prod-ui: 'false' # TODO: enable after testing
spec:
  enforcementAction: dryrun
  parameters: {}
  match:
    kinds:
      - apiGroups: ["networking.k8s.io"]
        kinds: ["Ingress"]
