{{/* we only need this policy in baremetal. Services in other clusters can scale freely */}}
{{- if eq .Values.cluster_type "baremetal" -}}

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkHighCPURequests
metadata:
  name: highcpurequests
  labels:
    on-prod-ui: 'true'
spec:
  enforcementAction: dryrun
  parameters: {}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod", "DaemonSet"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]

{{- end -}}
