kind: Ingress
apiVersion: networking.k8s.io/v1beta1

metadata:
  name: keppel-api
  annotations:
    kubernetes.io/tls-acme: "true"
    disco: "true"

spec:
  tls:
    - secretName: tls-keppel-api
      hosts:
        - 'keppel.{{ .Values.global.region }}.{{ .Values.global.tld }}'
        - '*.keppel.{{ .Values.global.region }}.{{ .Values.global.tld }}'
  rules:
    - host: 'keppel.{{ .Values.global.region }}.{{ .Values.global.tld }}'
      http:
        paths:
          - path: /
            backend:
              serviceName: keppel-api
              servicePort: 80
    - host: '*.keppel.{{ .Values.global.region }}.{{ .Values.global.tld }}'
      http:
        paths:
          - path: /
            backend:
              serviceName: keppel-api
              servicePort: 80

{{- if .Values.keppel.anycast_domain_name }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1

metadata:
  name: keppel-api-san
  annotations:
    kubernetes.io/tls-acme: "true"
    disco: "false"

spec:
  tls:
    - secretName: tls-keppel-api-san
      hosts:
        - '{{ .Values.keppel.anycast_domain_name }}'
        - '*.{{ .Values.keppel.anycast_domain_name }}'
  rules:
    - host: '{{ .Values.keppel.anycast_domain_name }}'
      http:
        paths:
          - path: /
            backend:
              serviceName: keppel-api
              servicePort: 80
    - host: '*.{{ .Values.keppel.anycast_domain_name }}'
      http:
        paths:
          - path: /
            backend:
              serviceName: keppel-api
              servicePort: 80
{{ end }}
