apiVersion: v1
kind: Secret
metadata:
  name: keppel-keys
data:
  issuer-key.pem:  {{ index .Values.keppel "issuer_key.pem" | b64enc }}
  {{- if (index .Values.keppel "previous_issuer_key.pem") }}
  previous-issuer-key.pem:  {{ index .Values.keppel "previous_issuer_key.pem" | b64enc }}
  {{- end }}
  {{- if (index .Values.keppel "anycast_issuer_key.pem") }}
  anycast-issuer-key.pem:  {{ index .Values.keppel "anycast_issuer_key.pem" | b64enc }}
  {{- end }}
  {{- if (index .Values.keppel "anycast_previous_issuer_key.pem") }}
  anycast-previous-issuer-key.pem:  {{ index .Values.keppel "anycast_previous_issuer_key.pem" | b64enc }}
  {{- end }}
