{{- $values := .Values.redfish }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullName" . }}
{{- if $values.namespace }}
  namespace: {{ $values.namespace }}
{{- end }}
  labels:
    app: {{ include "fullName" . }}
    type: exporter
spec:
  selector:
    matchLabels:
      app: {{ include "fullName" . }}
      type: exporter
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ include "fullName" . }} 
        type: exporter
    spec:
      containers:
      - name: {{ include "fullName" . }}
        image: {{ required ".Values.global.registry missing" .Values.global.registry }}/{{ required ".Values.redfish.image missing" $values.image }}:{{ required ".Values.redfish.tag missing" $values.tag  }}
        ports:
          - name: metrics
            containerPort: {{ $values.listen_port }}
        command:
          - /usr/bin/python3
        args:
          - -u
          - ./main.py
        env:
        - name: APP_ENV
          value: "{{ $values.app_env }}"
        - name: LISTEN_PORT
          value: "{{ $values.listen_port }}"
        - name: TIMEOUT
          value: "5"
        {{- if .Values.global.redfish_bm_username }}
        - name: REDFISH_BM_USERNAME
          value: {{ required "redfish_bm_username needs to be defined in global values" .Values.global.redfish_bm_username }}
        - name: REDFISH_BM_PASSWORD
          value: {{ required "redfish_bm_username needs to be defined in global values" .Values.global.redfish_bm_password }}
        {{- end }}
        {{- if .Values.global.redfish_cp_username }}
        - name: REDFISH_CP_USERNAME
          value: {{ required "redfish_cp_username needs to be defined in global values" .Values.global.redfish_cp_username }}
        - name: REDFISH_CP_PASSWORD
          value: {{ required "redfish_cp_password needs to be defined in global values" .Values.global.redfish_cp_password }}
        {{- end }}
        {{- if .Values.global.redfish_bb_username }}
        - name: REDFISH_BB_USERNAME
          value: {{ required "redfish_bb_username needs to be defined in global values" .Values.global.redfish_bb_username }}
        - name: REDFISH_BB_PASSWORD
          value: {{ required "redfish_bb_password needs to be defined in global values" .Values.global.redfish_bb_password }}
        {{- end }}
        resources:
          limits:
            memory: {{ required "$values.limits.memory missing" $values.limits.memory }}
            cpu: {{ required "$values.limits.cpu missing" $values.limits.cpu }}
          requests:
            memory: {{ required "$values.resources.memory missing" $values.resources.memory }}
            cpu: {{ required "$values.resources.cpu missing" $values.resources.cpu }}
