{{- if .Values.prometheus.operator.serviceMonitor.namespace }}
  namespace: {{ .Values.prometheus.operator.serviceMonitor.namespace }}
{{- end }}
  labels:
    app: {{ include "fullName" . }}
    type: exporter
{{- if .Values.prometheus.operator.serviceMonitor.selector }}
{{ toYaml .Values.prometheus.operator.serviceMonitor.selector | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "fullName" . }}
      type: exporter
  endpoints:
  - port: metrics
    interval: {{ .Values.prometheus.operator.serviceMonitor.interval }}
  namespaceSelector:
    any: true
  - job_name: 'redfish/bm'
    params:
      job: [redfish/bm]
    scrape_interval: {{ .Values.prometheus.operator.serviceMonitor.interval }}
    scrape_timeout: {{ .Values.prometheus.operator.serviceMonitor.scrapeTimeout }}
    file_sd_configs:
        - files :
          - /etc/prometheus/configmaps/atlas-netbox-sd/netbox.json
    metrics_path: /redfish
    relabel_configs:
      - source_labels: [job]
        regex: redfish/bm
        action: keep
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redfish-exporter:{{ .Values.redfish.listen_port }}

  - job_name: 'redfish/cp'
    params:
      job: [redfish/cp]
    scrape_interval: {{ .Values.prometheus.operator.serviceMonitor.interval }}
    scrape_timeout: {{ .Values.prometheus.operator.serviceMonitor.scrapeTimeout }}
    file_sd_configs:
        - files :
          - /etc/prometheus/configmaps/atlas-netbox-sd/netbox.json
    metrics_path: /redfish
    relabel_configs:
      - source_labels: [job]
        regex: redfish/cp
        action: keep
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redfish-exporter:{{ .Values.redfish.listen_port }}
      - source_labels: [__meta_serial]
        target_label: server_serial

  - job_name: 'redfish/bb'
    params:
      job: [redfish/bb]
    scrape_interval: {{ .Values.prometheus.operator.serviceMonitor.interval }}
    scrape_timeout: {{ .Values.prometheus.operator.serviceMonitor.scrapeTimeout }}
    file_sd_configs:
        - files :
          - /etc/prometheus/configmaps/atlas-netbox-sd/netbox.json
    metrics_path: /redfish
    relabel_configs:
      - source_labels: [job]
        regex: redfish/bb
        action: keep
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redfish-exporter:{{ .Values.redfish.listen_port }}
{{ end }}