roles:
- name: owner
  local:
    users: ["admin"]
  oidc:
    groups: ["CC_IAS_CONCOURSE_SYSTEM_ADMIN"]
- name: member
  github:
    teams:
    - "infrastructure-automation:ccloud-net-admins"
  oidc:
    groups: ["CC_IAS_TEAM_INFRAAUTOMATION"]
- name: pipeline-operator
  github:
    teams:
    - "infrastructure-automation:ccloud-l4"
- name: viewer
  github:
    orgs:
    - "cc"
    - "infrastructure-automation"
  oidc:
    groups: [
      "CC_IAS_TEAM_CORE",
      "CC_IAS_TEAM_IMAGE",
      "CC_IAS_TEAM_SERVICES",
      "CC_IAS_TEAM_SOLUTIONDEVELOPMENT",
      "CC_IAS_TEAM_SUPERVISION"
    ]
