roles:
- name: owner
  local:
    users: ["admin"]
  oidc:
    groups: ["CC_IAS_CONCOURSE_SYSTEM_ADMIN"]
- name: member
  github:
    teams: ["cc:ci-controlplane"]
  oidc:
    users: [
      "D062260",
      "C5267192",
      "C5328378",
      "C5329702"
    ]
- name: viewer
  github:
    orgs: ["cc"]
  oidc:
    groups: [
      "CC_IAS_TEAM_CORE",
      "CC_IAS_TEAM_IMAGE",
      "CC_IAS_TEAM_INFRAAUTOMATION",
      "CC_IAS_TEAM_SERVICES",
      "CC_IAS_TEAM_SOLUTIONDEVELOPMENT",
      "CC_IAS_TEAM_SUPERVISION"
    ]
