roles:
- name: owner
  local:
    users: ["admin"]
  oidc:
    groups: ["CC_IAS_CONCOURSE_SYSTEM_ADMIN"]
- name: member
  github:
    teams: ["cc:ci-core"]
  oidc:
    groups: ["CC_IAS_TEAM_CORE"]
- name: viewer
  github:
    orgs: ["cc"]
  oidc:
    groups: [
      "CC_IAS_TEAM_IMAGE",
      "CC_IAS_TEAM_INFRAAUTOMATION",
      "CC_IAS_TEAM_SERVICES",
      "CC_IAS_TEAM_SOLUTIONDEVELOPMENT",
      "CC_IAS_TEAM_SUPERVISION"
    ]
