kind: Deployment
apiVersion: apps/v1

metadata:
  name: barbican-api
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    system: openstack
    type: api
    component: barbican
spec:
  replicas: {{ required ".Values.api.replicas is missing" .Values.api.replicas }}
  revisionHistoryLimit: {{ .Values.pod.lifecycle.upgrades.deployments.revisionHistory }}
  strategy:
    type: {{ .Values.pod.lifecycle.upgrades.deployments.podReplacementStrategy }}
    {{ if eq .Values.pod.lifecycle.upgrades.deployments.podReplacementStrategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.pod.lifecycle.upgrades.deployments.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.pod.lifecycle.upgrades.deployments.rollingUpdate.maxSurge }}
    {{ end }}
  selector:
    matchLabels:
      name: barbican-api
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        name: barbican-api
{{ tuple . "barbican" "api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
    spec:
{{ tuple . "barbican" "api" | include "kubernetes_pod_anti_affinity" | indent 6 }}
      containers:
        - name: barbican-api
          image: {{required ".Values.global.registry is missing" .Values.global.registry }}/loci-barbican:{{required "Values.imageVersionBarbicanApi is missing" .Values.imageVersionBarbicanApi}}
          imagePullPolicy: IfNotPresent
          command:
            - dumb-init
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "/var/lib/openstack/bin/barbican-api"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "barbican-migration"
            - name: DEPENDENCY_SERVICE
              value: "barbican-mariadb,barbican-rabbitmq"
            {{- if .Values.sentry.enabled }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: barbican.DSN.python
            {{- end }}
          {{- if .Values.api.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.api.resources.limits.cpu | quote }}
              memory: {{ .Values.api.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.api.resources.requests.cpu | quote }}
              memory: {{ .Values.api.resources.requests.memory | quote }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{.Values.api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: barbican-api
              containerPort: {{.Values.api_port_internal}}
          volumeMounts:
            - name: etcbarbican
              mountPath: /etc/barbican
            - name: barbican-etc
              mountPath: /etc/barbican/barbican.conf
              subPath: barbican.conf
              readOnly: true
            - name: barbican-etc
              mountPath: /etc/barbican/barbican-api-paste.ini
              subPath: barbican-api-paste.ini
              readOnly: true
            - name: barbican-etc
              mountPath: /etc/barbican/policy.yaml
              subPath: policy.yaml
              readOnly: true
            - name: barbican-etc
              mountPath: /etc/barbican/logging.ini
              subPath: logging.ini
              readOnly: true
            {{- if .Values.watcher.enabled }}
            - name: barbican-etc
              mountPath: /etc/barbican/watcher.yaml
              subPath: watcher.yaml
              readOnly: true
            {{- end }}
            {{- if .Values.audit.enabled }}
            - name: barbican-etc
              mountPath: /etc/barbican/barbican_audit_map.yaml
              subPath: barbican_audit_map.yaml
              readOnly: true
            {{- end }}
            {{- if .Values.sapcc_rate_limit.enabled }}
            - name: barbican-etc
              mountPath: /etc/barbican/ratelimit.yaml
              subPath: ratelimit.yaml
              readOnly: true
            {{- end }}
        - name: lunaclient
          image: {{required ".Values.global.registry is missing" .Values.global.registry }}/loci-barbican:{{required "Values.luna.image is missing" .Values.luna.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: LUNACLIENT_REPO
              value: {{ .Values.lunaclient.repo }}
            - name: LUNACLIENT_KNOWN_HOSTS
              value: {{ .Values.lunaclient.known_hosts }}
            - name: LUNACLIENT_VIRTUALTOKEN00LABEL
              value: {{ .Values.lunaclient.VirtualToken.VirtualToken00Label }}
            - name: LUNACLIENT_VIRTUALTOKEN00SN
              value: {{ .Values.lunaclient.VirtualToken.VirtualToken00SN }}
            - name: LUNACLIENT_VIRTUALTOKEN00MEMBERS
              value: {{ .Values.lunaclient.VirtualToken.VirtualToken00Members }}
            - name: LUNACLIENT_VIRTUALTOKENACTIVERECOVERY
              value: {{ .Values.lunaclient.VirtualToken.VirtualTokenActiveRecovery }}
            - name: LUNACLIENT_SYNC
              value: {{ .Values.lunaclient.HASynchronize.sync }}
            - name: LUNACLIENT_HALOGSTATUS
              value: {{ .Values.lunaclient.HAConfiguration.haLogStatus }}
            - name: LUNACLIENT_RECONNATT
              value: {{ .Values.lunaclient.HAConfiguration.reconnAtt }}
            - name: LUNACLIENT_HAONLY
              value: {{ .Values.lunaclient.HAConfiguration.HAOnly }}
            - name: LUNACLIENT_HALOGPATH
              value: {{ .Values.lunaclient.HAConfiguration.haLogPath }}
            - name: LUNACLIENT_LOGLEN
              value: {{ .Values.lunaclient.HAConfiguration.logLen }}
            - name: LUNACLIENT_USER
              value: {{ .Values.lunaclient.conn.user }}
            - name: LUNACLIENT_PWD
              value: {{ .Values.lunaclient.conn.pwd }}
            - name: LUNACLIENT_IP
              value: {{ .Values.lunaclient.conn.ip }}
            - name: LUNACLIENT_PAR
              value: {{ .Values.lunaclient.conn.par }}
            - name: LUNACLIENT_LIBRARY_PATH
              value: {{ .Values.lunaclient.conn.library_path }}
            - name: LUNACLIENT_LOGIN
              value: {{ .Values.lunaclient.conn.login }}
            - name: LUNACLIENT_MKEK_LABEL
              value: {{ .Values.lunaclient.conn.mkek_label }}
            - name: LUNACLIENT_MKEK_LENGTH
              value: {{ .Values.lunaclient.conn.mkek_lenght }}
            - name: LUNACLIENT_HMAC_LABEL
              value: {{ .Values.lunaclient.conn.hmac_lable }}
            - name: LUNACLIENT_SLOT_ID
              value: {{ .Values.lunaclient.conn.slot_id }}
            - name: LUNACLIENT_TAR
              value: {{ .Values.lunaclient.conn.tar }}
            - name: LUNACLIENT_UNTAR
              value: {{ .Values.lunaclient.conn.untar }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            timeoutSeconds: 10
            periodSeconds: 60
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            timeoutSeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "400m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "128Mi"
        - name: statsd
          {{- if hasKey .Values.global "dockerHubMirror"}}
          image: {{.Values.global.dockerHubMirror}}/{{ .Values.statsd.image.repository }}:{{ .Values.statsd.image.tag }}
          {{- else }}
          image: "{{ .Values.statsd.image.repository }}:{{ .Values.statsd.image.tag }}"
          {{- end }}          
          imagePullPolicy: IfNotPresent
          args: [ --statsd.mapping-config=/etc/statsd/statsd-exporter.yaml ]
          {{- if .Values.statsd.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.statsd.resources.limits.cpu | quote }}
              memory: {{ .Values.statsd.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.statsd.resources.requests.cpu | quote }}
              memory: {{ .Values.statsd.resources.requests.memory | quote }}
          {{- end }}          
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{ .Values.statsd.port }}
          volumeMounts:
            - name: barbican-etc
              mountPath: /etc/statsd/statsd-exporter.yaml
              subPath: statsd-exporter.yaml
              readOnly: true

      volumes:
        - name: barbican-etc
          configMap:
            name: barbican-etc
        - name: etcbarbican
          emptyDir: {}
