apiVersion: v1
kind: Secret
metadata:
  name: concourse-backup
  labels:
    app: concourse-backup
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  os-password: {{ .Values.backup.os_password | b64enc | quote }}
