{{- if .Values.backup.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-backup
spec:
  selector:
    matchLabels:
      name: concourse-backup
  template:
    metadata:
      labels:
        name: concourse-backup
    spec:
      containers:
      - name: concourse-backup
        image: "{{ index .Values "backup" "image" }}:{{ index .Values "backup" "imageTag" }}"
        env:
        - name: MY_POD_NAME
          value: "{{ .Release.Name }}-postgresql"
        - name: MY_POD_NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: OS_AUTH_URL
          value: {{ .Values.backup.os_auth_url | quote }}
        - name: OS_AUTH_VERSION
          value: "3"
        - name: OS_USERNAME
          value: {{ .Values.backup.os_username | quote }}
        - name: OS_USER_DOMAIN_NAME
          value: {{ .Values.backup.os_user_domain | quote }}
        - name: OS_PROJECT_NAME
          value: {{ .Values.backup.os_project_name | quote }}
        - name: OS_PROJECT_DOMAIN_NAME
          value: {{ .Values.backup.os_project_domain | quote }}
        - name: OS_REGION_NAME
          value: {{ .Values.backup.os_region_name | quote }}
        - name: OS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: concourse-backup
              key: os-password
        - name: BACKUP_PGSQL_FULL
          value: {{ .Values.backup.interval_full | quote }}
        - name: PGSQL_HOST
          value: {{ .Release.Name }}-postgresql
        - name: PGSQL_USER
          value: {{ .Values.concourse.postgresql.postgresqlUsername | quote }}
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: postgresql-password
{{- end }}
