roles:
- name: owner
  local:
    users: ["admin"]
  oidc:
    groups: ["CC_IAS_CONCOURSE_SYSTEM_ADMIN"]
- name: member
  oidc:
    groups: ["CC_IAS_PARTNER_VMWARE"]
- name: viewer
  oidc:
    groups: [
      "CC_IAS_TEAM_CORE",
      "CC_IAS_TEAM_IMAGE",
      "CC_IAS_TEAM_INFRAAUTOMATION",
      "CC_IAS_TEAM_SERVICES",
      "CC_IAS_TEAM_SOLUTIONDEVELOPMENT",
      "CC_IAS_TEAM_SUPERVISION",
    ]
