{{- if .Values.mariadb.restore.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: metisdb-restore
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: metisdb-restore
    helm.sh/chart: {{ include "metis.chart" $ }}
    app.kubernetes.io/instance: metisdb-restore-{{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.mariadb.restore.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: metisdb-restore
            image: "{{ .Values.mariadb.restore.image.repo }}:{{ .Values.mariadb.restore.image.tag }}"
            volumeMounts:
            - name: restore-config
              mountPath: /config
          restartPolicy: OnFailure
          volumes:
          - name: restore-config
            configMap:
              name: metisdb-restore-config
{{- end }}