{{- if .Values.mariadb.restore.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: metisdb-restore-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: metisdb-restore
    helm.sh/chart: {{ include "metis.chart" $ }}
    app.kubernetes.io/instance: metisdb-restore-{{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
data:
  config.yaml: |
    swift:
      identity_endpoint:  https://identity-3.{{ .Values.global.region }}.cloud.sap/v3
      user_name: db_backup
      user_domain_name: Default
      project_name: "master"
      project_domain_name: "ccadmin"
      token: {{ .Values.mariadb.restore.swift_token }}
    mariadb:
      user_name: root
      password: {{ .Values.mariadb.root_password }}
      ip: {{ .Values.mariadb.name }}-mariadb
      port: {{ .Values.mariadb.port_public }}
    openstack_dbs:
{{- range $backup := .Values.mariadb.restore.backups }}
      - {{$backup | toYaml | nindent 8}}
{{- end }}
    additional_sql_file: {{ .Values.mariadb.restore.additional_sql_file }}
    download_dir: {{ .Values.mariadb.restore.backup_dir }}
    debug: {{ .Values.mariadb.restore.debug.enabled }}
    region: {{ .Values.global.region }}

  openstack_view.sql: |
    {{ .Values.mariadb.restore.openstack_view }}
    ALTER USER 'root'@'localhost' IDENTIFIED BY '{{.Values.mariadb.root_password}}';
    ALTER USER 'root'@'%' IDENTIFIED BY '{{.Values.mariadb.root_password}}';
    GRANT SELECT on {{.Values.mariadb.dbName}}.* to '{{.Values.global.metis.user}}'@'%' IDENTIFIED BY '{{.Values.global.metis.password}}';
{{- range $db := .Values.mariadb.restore.read_access }}
    GRANT SELECT on {{$db}}.* to '{{$.Values.global.metis.user}}'@'%' IDENTIFIED BY '{{$.Values.global.metis.password}}';
{{- end }}

{{- end }}
