apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-{{ include "prometheus.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: prometheus-{{ include "prometheus.name" . }}
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
          - memory
{{- if and .Values.resources .Values.resources.limits }}
        maxAllowed:
{{ toYaml .Values.resources.limits | indent 10 }}
{{- end }}
