kind: Secret
apiVersion: v1

metadata:
  name: mosquitto
data:
{{- if mustRegexMatch "^2\\.[0-9]+\\.[0-9]+" .Values.image.tag }}
  mosquitto.conf: {{ include "mosquitto_v2.conf" . | b64enc }}
{{- else }}
  mosquitto.conf: {{ include "mosquitto.conf" . | b64enc }}
  acl.conf: {{ include "acl.conf" .| b64enc}}
{{- end }}
{{- if .Values.tls.enabled }}
  ca.crt: {{ default "" .Values.tls.caCertificate | b64enc }}
  server.key: {{ default "" .Values.tls.privateKey | b64enc }}
  server.crt: {{ default "" .Values.tls.certificate | b64enc }}
{{- if .Values.tls.crl }}
  ca.crl: {{ .Values.tls.crl | b64enc }}
{{- end }}
{{- end }}
