{{- if .Values.envoy_external }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-etc-{{ .Values.cluster_name }}
  labels:
    system: openstack
    service: objectstore
    component: configuration

data:
  envoy.yaml: |
{{ include "envoy.yaml" . | indent 4 }}

{{- end }}
